= SAÉ S4 parcours D - Introduction générale
:author: Équipe pédagogique BUT Informatique de Rodez
:title-page: true
:icons: font
:toc: left
//:toc: left
:sectnums:

== Rappel du contenu du BO : SAÉ 4.Integ.01 : Intégration d’une application et gestion de projet


=== Compétences ciblées :

* Développer — c’est-à-dire concevoir, coder, tester et intégrer — une solution informatique pour un client.
* Proposer des applications informatiques optimisées en fonction de critères spécifiques : temps d’exécution, précision,
consommation de ressources..
* Installer, configurer, mettre à disposition, maintenir en conditions opérationnelles des infrastructures, des services et des
réseaux et optimiser le système informatique d’une organisation
* Concevoir, gérer, administrer et exploiter les données de l’entreprise et mettre à disposition toutes les informations pour
un bon pilotage de l’entreprise
* Satisfaire les besoins des utilisateurs au regard de la chaîne de valeur du client, organiser et piloter un projet informatique
avec des méthodes classiques ou agiles
* Acquérir, développer et exploiter les aptitudes nécessaires pour travailler efficacement dans une équipe informatique

=== Objectifs et problématique professionnelle :

La problématique professionnelle est de mettre en place, au sein de l’équipe, l’organisation du projet et d’intégrer un progiciel
dans un système d’information en garantissant la faisabilité et en suivant une démarche de développement itérative ou incrémentale. Après avoir analysé les processus métiers et les besoins du client, il sera nécessaire d’intégrer et adapter un progiciel
(ou module) pour répondre à cette demande. Il sera nécessaire veiller aux caractéristiques de qualité définies par l’entreprise.

=== Descriptif générique :
En partant d’un système d’information existant, l’équipe devra en évaluer l’adéquation aux processus métiers, la qualité logicielle
et détecter les éventuelles failles de sécurité. L’objectif est d’intégrer un progiciel améliorant l’ensemble de ces aspects. De plus,
l’impact environnemental devra être évalué et, si possible, amélioré.

Les livrables attendus généralement dans le monde professionnel sont :

* Document de suivi de projet
* Étude des processus métiers
* Étude comparative des solutions
* Spécifications techniques finalisées
* Revue finale du projet


=== Apprentissages critiques :

* AC21.04 | Vérifier et valider la qualité de l’application par les tests
* AC22.02 | Utiliser des techniques algorithmiques adaptées pour des problèmes complexes (par ex. recherche opérationnelle, méthodes arborescentes, optimisation globale, intelligence artificielle...)
* AC22.03 | Comprendre les enjeux et moyens de sécurisation des données et du code
* AC22.04 | Évaluer l’impact environnemental et sociétal des solutions proposées
* AC23.03 | Sécuriser les services et données d’un système
* AC24.01 | Optimiser les modèles de données de l’entreprise
* AC24.02 | Assurer la sécurité des données (intégrité et confidentialité)
* AC25.02 | Formaliser les besoins du client et de l’utilisateur
* AC25.03 | Identifier les critères de faisabilité d’un projet informatique
* AC25.04 | Définir et mettre en oeuvre une démarche de suivi de projet
* AC26.02 | Appliquer une démarche pour intégrer une équipe informatique au sein d’une organisation
* AC26.03 | Mobiliser les compétences interpersonnelles pour travailler dans une équipe informatique
* AC26.04 | Rendre compte de son activité professionnelle

=== Ressources mobilisées et combinées :

* R4.01 | Architecture logicielle
* R4.02 | Qualité de développement
* R4.03 | Qualité et au-delà du relationnel
* R4.04 | Méthodes d’optimisation
* R4.05 | Anglais
* R4.06 | Communication interne
* R4.Integ.08 | Réseau avancé
* R4.Integ.09 | Outils mathématiques pour la gestion
* R4.Integ.10 | Management avancé des systèmes d’information

== Structure de la description de la SAÉ

=== Le cahier des charges

Le cahier des charges du projet présente les exigences fonctionnelles et extra-fonctionnelles au démarrage du projet.

=== Le plan de management de projet (PMP)

Le PMP décrit la méthode et les livrables attendus au démarrage du projet. Le PMP est commun à l'ensemble des projets.